Repository googleapis/python-dialogflow-cx, pull requests merged in 2022-06, with the labels that each got.

#396 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: dialogflow, size: xs

#395 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: dialogflow, size: s

#399 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: dialogflow, size: s

#400 fix(deps): require protobuf<4.0.0 on v0 branch
  setup.py
Labels: api: dialogflow, size: xs

#409 chore: Update dialogflow_cx_webhook snippet to match NodeJS
  noxfile.py
  samples/snippets/webhook.py
  samples/snippets/webhook_test.py
Labels: api: dialogflow, size: s

#410 chore: Dialogflow cx v3 webhook validate form parameter
  samples/snippets/webhook_validate_form_parameter.py
  samples/snippets/webhook_validate_form_parameter_test.py
Labels: api: dialogflow, size: m

#411 chore: update dialogflow_cx_v3_webhook_configure_session_parameters
  samples/snippets/webhook_configure_session_parameters.py
  samples/snippets/webhook_configure_session_parameters_test.py
Labels: api: dialogflow, size: s

#412 chore: Remove refactored webhook snippets
  samples/snippets/webhook_configure_optional_or_required_form_parameters.py
  samples/snippets/webhook_configure_optional_or_required_form_parameters_test.py
  samples/snippets/webhook_configure_session_parameters_enable_agent_response.py
  samples/snippets/webhook_configure_session_parameters_enable_agent_response_test.py
  samples/snippets/webhook_configure_session_parameters_trigger_transition.py
  samples/snippets/webhook_configure_session_parameters_trigger_transition_test.py
Labels: api: dialogflow, size: l
